# -*- coding: utf-8 -*-
"""Algoritmo PROFIT Ejemplo Agrocash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tryrsLKn8qr2OQqn_tp8VYr4izZXIeu2
"""

using JuMP, GLPK

# Create model object
model = Model(GLPK.Optimizer);

# Define crop yields matrix (in tons per hectare)
nl     = 5;
nc     = 5 ;

s_crops = 1:nc;
s_lands = 1:nl;

yield = [1.5 1.0 1.2 2.5 2.0;
         2.5 2.0 1.5 1.2 1.0;
         1.0 1.5 2.0 2.0 2.5;
         2.0 1.5 1.0 1.5 2.0;
        1.2 2.0 2.5 1.0 1.5];

c      = [10, 15, 12, 17, 13];
demand = [100, 200, 120, 150, 300]

atotal = 600
afmax  = 0.2
afmin  = 0.05;

@variable(model, area[s_crops, s_lands] >= 0);   # [acres]
@variable(model, crop[s_crops]          >= 0);   # [Ton]
@variable(model, profit                 >= 0);   # [$]

@constraint(model, c_crop[i in s_crops], crop[i] ==  sum(yield[i,j]*area[i,j] for j in s_lands));

@constraint(model, d_crop[i in s_crops], crop[i] >= demand[i]) ;

@constraint(model,  sum(area) == atotal) ;

@constraint(model,  a_cont[i in s_crops, j in s_lands], area[i,j] <= afmax*atotal) ;

@constraint(model,  ac_cont[j in s_lands], sum(area[i,j] for i in s_crops) <= afmax*atotal) ;

@constraint(model,  ar_cont[i in s_crops], sum(area[i,j] for j in s_lands) <= afmax*atotal) ;

@constraint(model,  profit == sum(c[i]*crop[i] for i in s_crops)) ;

@objective(model, Max, profit );

optimize!(model)

solution_summary(model)

# Función auxiliar: quita negativos y redondea a 0 decimales
r(x) = round(max(x, 0); digits=0)

println("Profit: ", r(objective_value(model)))

for i = 1:nc
    println("Crop : ", i,
            "  Amount: ", r(value(crop[i])),
            "  Demand: ", demand[i])
end

println("")

for i = 1:nc
    println("Crop : ", i, "  ",
            r(value(area[i,1])), "  ",
            r(value(area[i,2])), "  ",
            r(value(area[i,3])), "  ",
            r(value(area[i,4])), "  ",
            r(value(area[i,5])))
end

